### ISSUE TITLE
local install latest version of ruby (2.3.1)

### ISSUE THREAD

**Issue by f8f8ff** [f8f8ff/f8f8ff.github.io#2]

**Comment by f8f8ff** [comment]
Installation requires [installation method](https://www.ruby-lang.org/en/documentation/installation/#homebrew): 
- *Installer:* several options, including installing a) RVM; b) ruby-build (+ rbenv); c) ruby-install (+ wget). 
- *Package mgmt:* installing Homebrew. 
- *Source:* “Using the third-party tools or package managers might be a better idea, though, because the installed Ruby won’t be managed by any tools.” 

Recommendation?

**Comment by courte** [comment]
It looks like I use rbenv, but I think I have some familiarity with rvm, too. Why don't you start by using homebrew to install rbenv to install Ruby? (If you decide you like a different manager in the future it won't be hard to tear this all down.)

`rbenv help` will show you the commands available to you.

**Comment by f8f8ff** [comment]
:thumbsup:
