### ISSUE TITLE
research wordpress to jekyll export

### ISSUE THREAD

**Issue by f8f8ff** [f8f8ff/f8f8ff.github.io#4]
- [x] Review documentation
- [x] Export from temp/test WordPress account

**Comment by courte** [comment]
http://import.jekyllrb.com/docs/wordpress/ is the importer for self-hosted Wordpress sites. It looks like there are options for extracting both the images and the posts themselves. I've only been able to test with a Wordpress.com blog thus far, but I'm confident we can work out the import options for hosted servers as well.
